names:
  organization: 'OSS Org'
  product: 'OSS Product'
version: 
  major: 0
  minor: 0
  patch: 3
article:
  childArticles:
    display: true
    count: 7 
    titleTrunc: 90
    descTrunc: 90
  nextPrev: 
    display: true
    trunc: 35
  chat: 
    display: true
  toc: 
    display: true
